"""create tables

Revision ID: 9d0b10830b9d
Revises: 
Create Date: 2026-03-30 22:08:58.907403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0b10830b9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('tournament_type', sa.Enum('ELIMINATION', 'GROUPS', 'CHAMPIONSHIP', name='tournamenttype'), nullable=False),
    sa.Column('elimination_type', sa.Enum('SINGLE', 'DOUBLE', name='eliminationtype'), nullable=True),
    sa.Column('championship_legs', sa.Enum('SINGLE', 'DOUBLE', name='championshiplegs'), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('group_count', sa.Integer(), nullable=True),
    sa.Column('teams_per_group', sa.Integer(), nullable=True),
    sa.Column('qualified_per_group', sa.Integer(), nullable=True),
    sa.Column('elimination_round', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION', 'DRAW', 'IN_PROGRESS', 'FINISHED', name='tournamentstatus'), nullable=True),
    sa.Column('creator_session', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('pseudo', sa.String(length=50), nullable=False),
    sa.Column('dll_idx', sa.String(length=20), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_logo_url', sa.String(length=255), nullable=True),
    sa.Column('dll_division', sa.Integer(), nullable=True),
    sa.Column('dll_played', sa.Integer(), nullable=True),
    sa.Column('dll_won', sa.Integer(), nullable=True),
    sa.Column('dll_lost', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='playerstatus'), nullable=True),
    sa.Column('group_id', sa.String(length=5), nullable=True),
    sa.Column('is_creator', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('home_player_id', sa.String(length=36), nullable=False),
    sa.Column('away_player_id', sa.String(length=36), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_score_agg', sa.Integer(), nullable=True),
    sa.Column('away_score_agg', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('phase', sa.Enum('GROUP', 'R16', 'QF', 'SF', 'FINAL', 'CHAMPIONSHIP', 'DOUBLE_FIRST', 'DOUBLE_SECOND', name='matchphase'), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'PENDING_VALIDATION', 'VALIDATED', 'MANUAL', name='matchstatus'), nullable=True),
    sa.Column('dll_match_timestamp', sa.String(length=20), nullable=True),
    sa.Column('stats_data', sa.JSON(), nullable=True),
    sa.Column('home_scorers', sa.JSON(), nullable=True),
    sa.Column('away_scorers', sa.JSON(), nullable=True),
    sa.Column('motm', sa.String(length=80), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['away_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['home_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('players')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
