"""create tables tournaments players matches

Revision ID: e30f62179756
Revises: 9d0b10830b9d
Create Date: 2026-03-30 22:09:48.300309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30f62179756'
down_revision = '9d0b10830b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
